from collections.abc import Sequence

class List:
    def __init__(self, name: str, *, message: str, choices: Sequence[object], default: object = ...) -> None: ...

class Text:
    def __init__(self, name: str, *, message: str) -> None: ...

class Checkbox:
    def __init__(self, name: str, *, message: str, choices: Sequence[object]) -> None: ...

def prompt(questions: object) -> dict[str, object] | None: ...
