from collections.abc import Mapping

class MultipartEncoder:
    content_type: str

    def __init__(self, *, fields: Mapping[str, object]) -> None: ...
    def read(self, size: int = ...) -> bytes: ...
    def to_string(self) -> bytes: ...
    # The real encoder exposes its size as a `len` property; it has no __len__,
    # so built-in len(encoder) raises TypeError at runtime.
    @property
    def len(self) -> int: ...
