from collections.abc import Mapping

class MultipartEncoder:
    content_type: str

    def __init__(self, *, fields: Mapping[str, object]) -> None: ...
    def read(self, size: int = ...) -> bytes: ...
    def __len__(self) -> int: ...
