#!/usr/bin/env bash
set -euo pipefail

ROOT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
CHECK_MODE="${1:-}"

if [[ -n "${CHECK_MODE}" && "${CHECK_MODE}" != "--check" ]]; then
  echo "Usage: $0 [--check]"
  exit 2
fi

hash_policy() {
  sha256sum "$@" | sha256sum | awk '{print $1}'
}

if [[ "${CHECK_MODE}" == "--check" ]]; then
  runtime_hash="$(hash_policy "${ROOT_DIR}/requirements.txt")"
  dev_hash="$(hash_policy "${ROOT_DIR}/requirements.txt" "${ROOT_DIR}/requirements-dev.txt")"

  runtime_recorded="$(awk -F': ' '/^# policy-sha256:/ {print $2; exit}' "${ROOT_DIR}/constraints.txt")"
  dev_recorded="$(awk -F': ' '/^# policy-sha256:/ {print $2; exit}' "${ROOT_DIR}/constraints-dev.txt")"

  [[ "${runtime_hash}" == "${runtime_recorded}" ]] || {
    echo "constraints.txt is stale for requirements.txt"
    echo "Run ./scripts/update_constraints.sh"
    exit 1
  }

  [[ "${dev_hash}" == "${dev_recorded}" ]] || {
    echo "constraints-dev.txt is stale for requirements.txt/requirements-dev.txt"
    echo "Run ./scripts/update_constraints.sh"
    exit 1
  }

  echo "Constraint files are up-to-date with policy files."
  exit 0
fi

TMP_DIR="$(mktemp -d)"
cleanup() {
  rm -rf "${TMP_DIR}"
}
trap cleanup EXIT

runtime_hash="$(hash_policy "${ROOT_DIR}/requirements.txt")"
dev_hash="$(hash_policy "${ROOT_DIR}/requirements.txt" "${ROOT_DIR}/requirements-dev.txt")"

python3 -m venv "${TMP_DIR}/venv"
# shellcheck disable=SC1091
source "${TMP_DIR}/venv/bin/activate"

python -m pip install --upgrade pip
python -m pip install -r "${ROOT_DIR}/requirements.txt"
{
  echo "# Generated by scripts/update_constraints.sh"
  echo "# policy-sha256: ${runtime_hash}"
  pip freeze --all | sort
} > "${ROOT_DIR}/constraints.txt"

python -m pip install -r "${ROOT_DIR}/requirements-dev.txt" -c "${ROOT_DIR}/constraints.txt"
{
  echo "# Generated by scripts/update_constraints.sh"
  echo "# policy-sha256: ${dev_hash}"
  pip freeze --all | sort
} > "${ROOT_DIR}/constraints-dev.txt"

echo "Updated constraints.txt and constraints-dev.txt"
